// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protocol/user.proto

package protobuf

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UserInfo struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Sex                  string   `protobuf:"bytes,4,opt,name=sex,proto3" json:"sex,omitempty"`
	Phone                string   `protobuf:"bytes,5,opt,name=phone,proto3" json:"phone,omitempty"`
	Role                 string   `protobuf:"bytes,6,opt,name=role,proto3" json:"role,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserInfo) Reset()         { *m = UserInfo{} }
func (m *UserInfo) String() string { return proto.CompactTextString(m) }
func (*UserInfo) ProtoMessage()    {}
func (*UserInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_fe658c3c35e8c4bc, []int{0}
}

func (m *UserInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfo.Unmarshal(m, b)
}
func (m *UserInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfo.Marshal(b, m, deterministic)
}
func (m *UserInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfo.Merge(m, src)
}
func (m *UserInfo) XXX_Size() int {
	return xxx_messageInfo_UserInfo.Size(m)
}
func (m *UserInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfo.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfo proto.InternalMessageInfo

func (m *UserInfo) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *UserInfo) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *UserInfo) GetSex() string {
	if m != nil {
		return m.Sex
	}
	return ""
}

func (m *UserInfo) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *UserInfo) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

type SignUpReq struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	RePassword           string   `protobuf:"bytes,3,opt,name=re_password,json=rePassword,proto3" json:"re_password,omitempty"`
	Sex                  string   `protobuf:"bytes,4,opt,name=sex,proto3" json:"sex,omitempty"`
	Phone                string   `protobuf:"bytes,5,opt,name=phone,proto3" json:"phone,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignUpReq) Reset()         { *m = SignUpReq{} }
func (m *SignUpReq) String() string { return proto.CompactTextString(m) }
func (*SignUpReq) ProtoMessage()    {}
func (*SignUpReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_fe658c3c35e8c4bc, []int{1}
}

func (m *SignUpReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignUpReq.Unmarshal(m, b)
}
func (m *SignUpReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignUpReq.Marshal(b, m, deterministic)
}
func (m *SignUpReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignUpReq.Merge(m, src)
}
func (m *SignUpReq) XXX_Size() int {
	return xxx_messageInfo_SignUpReq.Size(m)
}
func (m *SignUpReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SignUpReq.DiscardUnknown(m)
}

var xxx_messageInfo_SignUpReq proto.InternalMessageInfo

func (m *SignUpReq) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *SignUpReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *SignUpReq) GetRePassword() string {
	if m != nil {
		return m.RePassword
	}
	return ""
}

func (m *SignUpReq) GetSex() string {
	if m != nil {
		return m.Sex
	}
	return ""
}

func (m *SignUpReq) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

type SignUpRsp struct {
	Code                 int64    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Token                string   `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignUpRsp) Reset()         { *m = SignUpRsp{} }
func (m *SignUpRsp) String() string { return proto.CompactTextString(m) }
func (*SignUpRsp) ProtoMessage()    {}
func (*SignUpRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_fe658c3c35e8c4bc, []int{2}
}

func (m *SignUpRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignUpRsp.Unmarshal(m, b)
}
func (m *SignUpRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignUpRsp.Marshal(b, m, deterministic)
}
func (m *SignUpRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignUpRsp.Merge(m, src)
}
func (m *SignUpRsp) XXX_Size() int {
	return xxx_messageInfo_SignUpRsp.Size(m)
}
func (m *SignUpRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_SignUpRsp.DiscardUnknown(m)
}

var xxx_messageInfo_SignUpRsp proto.InternalMessageInfo

func (m *SignUpRsp) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *SignUpRsp) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *SignUpRsp) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type SignInReq struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignInReq) Reset()         { *m = SignInReq{} }
func (m *SignInReq) String() string { return proto.CompactTextString(m) }
func (*SignInReq) ProtoMessage()    {}
func (*SignInReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_fe658c3c35e8c4bc, []int{3}
}

func (m *SignInReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignInReq.Unmarshal(m, b)
}
func (m *SignInReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignInReq.Marshal(b, m, deterministic)
}
func (m *SignInReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignInReq.Merge(m, src)
}
func (m *SignInReq) XXX_Size() int {
	return xxx_messageInfo_SignInReq.Size(m)
}
func (m *SignInReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SignInReq.DiscardUnknown(m)
}

var xxx_messageInfo_SignInReq proto.InternalMessageInfo

func (m *SignInReq) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *SignInReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type SignInRsp struct {
	Code                 int64    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Token                string   `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignInRsp) Reset()         { *m = SignInRsp{} }
func (m *SignInRsp) String() string { return proto.CompactTextString(m) }
func (*SignInRsp) ProtoMessage()    {}
func (*SignInRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_fe658c3c35e8c4bc, []int{4}
}

func (m *SignInRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignInRsp.Unmarshal(m, b)
}
func (m *SignInRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignInRsp.Marshal(b, m, deterministic)
}
func (m *SignInRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignInRsp.Merge(m, src)
}
func (m *SignInRsp) XXX_Size() int {
	return xxx_messageInfo_SignInRsp.Size(m)
}
func (m *SignInRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_SignInRsp.DiscardUnknown(m)
}

var xxx_messageInfo_SignInRsp proto.InternalMessageInfo

func (m *SignInRsp) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *SignInRsp) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *SignInRsp) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type AuthReq struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthReq) Reset()         { *m = AuthReq{} }
func (m *AuthReq) String() string { return proto.CompactTextString(m) }
func (*AuthReq) ProtoMessage()    {}
func (*AuthReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_fe658c3c35e8c4bc, []int{5}
}

func (m *AuthReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthReq.Unmarshal(m, b)
}
func (m *AuthReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthReq.Marshal(b, m, deterministic)
}
func (m *AuthReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthReq.Merge(m, src)
}
func (m *AuthReq) XXX_Size() int {
	return xxx_messageInfo_AuthReq.Size(m)
}
func (m *AuthReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthReq.DiscardUnknown(m)
}

var xxx_messageInfo_AuthReq proto.InternalMessageInfo

func (m *AuthReq) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type AuthRsp struct {
	Code                 int64    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Username             string   `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthRsp) Reset()         { *m = AuthRsp{} }
func (m *AuthRsp) String() string { return proto.CompactTextString(m) }
func (*AuthRsp) ProtoMessage()    {}
func (*AuthRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_fe658c3c35e8c4bc, []int{6}
}

func (m *AuthRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthRsp.Unmarshal(m, b)
}
func (m *AuthRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthRsp.Marshal(b, m, deterministic)
}
func (m *AuthRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthRsp.Merge(m, src)
}
func (m *AuthRsp) XXX_Size() int {
	return xxx_messageInfo_AuthRsp.Size(m)
}
func (m *AuthRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthRsp.DiscardUnknown(m)
}

var xxx_messageInfo_AuthRsp proto.InternalMessageInfo

func (m *AuthRsp) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *AuthRsp) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *AuthRsp) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *AuthRsp) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type GetPersonalInfoReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPersonalInfoReq) Reset()         { *m = GetPersonalInfoReq{} }
func (m *GetPersonalInfoReq) String() string { return proto.CompactTextString(m) }
func (*GetPersonalInfoReq) ProtoMessage()    {}
func (*GetPersonalInfoReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_fe658c3c35e8c4bc, []int{7}
}

func (m *GetPersonalInfoReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPersonalInfoReq.Unmarshal(m, b)
}
func (m *GetPersonalInfoReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPersonalInfoReq.Marshal(b, m, deterministic)
}
func (m *GetPersonalInfoReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPersonalInfoReq.Merge(m, src)
}
func (m *GetPersonalInfoReq) XXX_Size() int {
	return xxx_messageInfo_GetPersonalInfoReq.Size(m)
}
func (m *GetPersonalInfoReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPersonalInfoReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetPersonalInfoReq proto.InternalMessageInfo

type GetPersonalInfoRsp struct {
	User                 *UserInfo `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetPersonalInfoRsp) Reset()         { *m = GetPersonalInfoRsp{} }
func (m *GetPersonalInfoRsp) String() string { return proto.CompactTextString(m) }
func (*GetPersonalInfoRsp) ProtoMessage()    {}
func (*GetPersonalInfoRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_fe658c3c35e8c4bc, []int{8}
}

func (m *GetPersonalInfoRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPersonalInfoRsp.Unmarshal(m, b)
}
func (m *GetPersonalInfoRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPersonalInfoRsp.Marshal(b, m, deterministic)
}
func (m *GetPersonalInfoRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPersonalInfoRsp.Merge(m, src)
}
func (m *GetPersonalInfoRsp) XXX_Size() int {
	return xxx_messageInfo_GetPersonalInfoRsp.Size(m)
}
func (m *GetPersonalInfoRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPersonalInfoRsp.DiscardUnknown(m)
}

var xxx_messageInfo_GetPersonalInfoRsp proto.InternalMessageInfo

func (m *GetPersonalInfoRsp) GetUser() *UserInfo {
	if m != nil {
		return m.User
	}
	return nil
}

func init() {
	proto.RegisterType((*UserInfo)(nil), "user.UserInfo")
	proto.RegisterType((*SignUpReq)(nil), "user.SignUpReq")
	proto.RegisterType((*SignUpRsp)(nil), "user.SignUpRsp")
	proto.RegisterType((*SignInReq)(nil), "user.SignInReq")
	proto.RegisterType((*SignInRsp)(nil), "user.SignInRsp")
	proto.RegisterType((*AuthReq)(nil), "user.AuthReq")
	proto.RegisterType((*AuthRsp)(nil), "user.AuthRsp")
	proto.RegisterType((*GetPersonalInfoReq)(nil), "user.GetPersonalInfoReq")
	proto.RegisterType((*GetPersonalInfoRsp)(nil), "user.GetPersonalInfoRsp")
}

func init() { proto.RegisterFile("protocol/user.proto", fileDescriptor_fe658c3c35e8c4bc) }

var fileDescriptor_fe658c3c35e8c4bc = []byte{
	// 355 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x53, 0xcf, 0x4e, 0xf2, 0x40,
	0x10, 0xff, 0xfa, 0xb5, 0x20, 0x0c, 0x51, 0xcc, 0xca, 0xa1, 0xe9, 0x05, 0xd3, 0x83, 0xf1, 0x60,
	0x30, 0xc1, 0x8b, 0x57, 0xe3, 0x81, 0xf4, 0x46, 0x6a, 0x38, 0x1b, 0x84, 0x11, 0x8c, 0xb0, 0xbb,
	0xec, 0x96, 0xe8, 0xc9, 0x27, 0xf0, 0xed, 0x7c, 0x21, 0x33, 0xb3, 0x6d, 0x53, 0x20, 0x1a, 0x95,
	0xdb, 0xfc, 0xfe, 0x64, 0xf6, 0x37, 0x9d, 0x29, 0x9c, 0x68, 0xa3, 0x32, 0x35, 0x51, 0x8b, 0xcb,
	0xb5, 0x45, 0xd3, 0x63, 0x24, 0x02, 0xaa, 0xe3, 0x37, 0x68, 0x8c, 0x2c, 0x9a, 0x44, 0x3e, 0x2a,
	0x11, 0x41, 0x83, 0x38, 0x39, 0x5e, 0x62, 0xe8, 0x9d, 0x7a, 0xe7, 0xcd, 0xb4, 0xc4, 0xa4, 0xe9,
	0xb1, 0xb5, 0x2f, 0xca, 0x4c, 0xc3, 0xff, 0x4e, 0x2b, 0xb0, 0x38, 0x06, 0xdf, 0xe2, 0x6b, 0x18,
	0x30, 0x4d, 0xa5, 0xe8, 0x40, 0x4d, 0xcf, 0x95, 0xc4, 0xb0, 0xc6, 0x9c, 0x03, 0x42, 0x40, 0x60,
	0xd4, 0x02, 0xc3, 0x3a, 0x93, 0x5c, 0xc7, 0xef, 0x1e, 0x34, 0xef, 0x9e, 0x66, 0x72, 0xa4, 0x53,
	0x5c, 0xfd, 0x39, 0x41, 0x17, 0x5a, 0x06, 0xef, 0x4b, 0xd9, 0x67, 0x19, 0x0c, 0x0e, 0x7f, 0x19,
	0x31, 0x1e, 0x94, 0x69, 0xac, 0xa6, 0xbc, 0x13, 0x35, 0x75, 0x49, 0xfc, 0x94, 0x6b, 0x6a, 0xb4,
	0xb4, 0xb3, 0x3c, 0x00, 0x95, 0xd4, 0x28, 0x53, 0xcf, 0x28, 0xf3, 0x57, 0x1d, 0x88, 0x6f, 0x5d,
	0xa3, 0x44, 0xee, 0x31, 0x56, 0x91, 0x26, 0x91, 0xfb, 0xa6, 0xe9, 0xc2, 0xc1, 0xcd, 0x3a, 0x9b,
	0x53, 0x96, 0xd2, 0xe0, 0x55, 0x0d, 0xb3, 0xdc, 0xf0, 0xe3, 0x77, 0xaa, 0x23, 0xf9, 0xdf, 0x8c,
	0x14, 0x6c, 0x8d, 0xd4, 0x01, 0x31, 0xc0, 0x6c, 0x88, 0xc6, 0x2a, 0x39, 0x5e, 0xd0, 0xd9, 0xa5,
	0xb8, 0x8a, 0xaf, 0x77, 0x59, 0xab, 0x45, 0x0c, 0x7c, 0xa3, 0x9c, 0xa4, 0xd5, 0x3f, 0xea, 0xf1,
	0xf1, 0x16, 0xd7, 0x9a, 0xb2, 0xd6, 0xff, 0xf0, 0x20, 0x20, 0x4a, 0x5c, 0x40, 0xdd, 0x6d, 0x4e,
	0xb4, 0x9d, 0xb1, 0xbc, 0xaa, 0x68, 0x93, 0xb0, 0x3a, 0xfe, 0x57, 0xb8, 0x13, 0x59, 0x75, 0xf3,
	0xb2, 0xa2, 0x4d, 0x82, 0xdd, 0x03, 0x68, 0x6f, 0xc5, 0x13, 0xa1, 0x73, 0xed, 0xce, 0x12, 0x7d,
	0xa1, 0x70, 0xa3, 0x33, 0x08, 0xe8, 0x33, 0x8b, 0x43, 0xe7, 0xc9, 0x77, 0x12, 0x55, 0x21, 0xf9,
	0x1e, 0xea, 0xfc, 0x8b, 0x5e, 0x7d, 0x06, 0x00, 0x00, 0xff, 0xff, 0x7b, 0xa4, 0x66, 0x81, 0xb9,
	0x03, 0x00, 0x00,
}
