// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: protocol/user.proto

package protobuf

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for User service

func NewUserEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for User service

type UserService interface {
	SignUp(ctx context.Context, in *SignUpReq, opts ...client.CallOption) (*SignUpRsp, error)
	SignIn(ctx context.Context, in *SignInReq, opts ...client.CallOption) (*SignInRsp, error)
	Auth(ctx context.Context, in *AuthReq, opts ...client.CallOption) (*AuthRsp, error)
}

type userService struct {
	c    client.Client
	name string
}

func NewUserService(name string, c client.Client) UserService {
	return &userService{
		c:    c,
		name: name,
	}
}

func (c *userService) SignUp(ctx context.Context, in *SignUpReq, opts ...client.CallOption) (*SignUpRsp, error) {
	req := c.c.NewRequest(c.name, "User.SignUp", in)
	out := new(SignUpRsp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) SignIn(ctx context.Context, in *SignInReq, opts ...client.CallOption) (*SignInRsp, error) {
	req := c.c.NewRequest(c.name, "User.SignIn", in)
	out := new(SignInRsp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) Auth(ctx context.Context, in *AuthReq, opts ...client.CallOption) (*AuthRsp, error) {
	req := c.c.NewRequest(c.name, "User.Auth", in)
	out := new(AuthRsp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for User service

type UserHandler interface {
	SignUp(context.Context, *SignUpReq, *SignUpRsp) error
	SignIn(context.Context, *SignInReq, *SignInRsp) error
	Auth(context.Context, *AuthReq, *AuthRsp) error
}

func RegisterUserHandler(s server.Server, hdlr UserHandler, opts ...server.HandlerOption) error {
	type user interface {
		SignUp(ctx context.Context, in *SignUpReq, out *SignUpRsp) error
		SignIn(ctx context.Context, in *SignInReq, out *SignInRsp) error
		Auth(ctx context.Context, in *AuthReq, out *AuthRsp) error
	}
	type User struct {
		user
	}
	h := &userHandler{hdlr}
	return s.Handle(s.NewHandler(&User{h}, opts...))
}

type userHandler struct {
	UserHandler
}

func (h *userHandler) SignUp(ctx context.Context, in *SignUpReq, out *SignUpRsp) error {
	return h.UserHandler.SignUp(ctx, in, out)
}

func (h *userHandler) SignIn(ctx context.Context, in *SignInReq, out *SignInRsp) error {
	return h.UserHandler.SignIn(ctx, in, out)
}

func (h *userHandler) Auth(ctx context.Context, in *AuthReq, out *AuthRsp) error {
	return h.UserHandler.Auth(ctx, in, out)
}
